import {
  FileType,
  Material,
  MaterialCategory,
  MaterialType,
} from "@/types/Material";

// Mock data for materials
export const mockMaterials: Material[] = [
  // JEE Materials
  {
    id: 1,
    name: "Chemical Bonding Notes",
    file_type: FileType.PDF,
    file_url: "url1",
    chapter: 1,
    class: 11,
    type: MaterialType.MATERIAL,
    category: MaterialCategory.JEE,
  },
  {
    id: 2,
    name: "Electrochemistry PYQ 2022",
    file_type: FileType.PDF,
    file_url: "url2",
    chapter: 2,
    class: 12,
    type: MaterialType.PYQ,
    category: MaterialCategory.JEE,
  },
  {
    id: 3,
    name: "Organic Chemistry Solutions",
    file_type: FileType.PDF,
    file_url: "url3",
    chapter: 3,
    class: 11,
    type: MaterialType.SOLUTION,
    category: MaterialCategory.JEE,
  },
  {
    id: 4,
    name: "Atomic Structure Notes",
    file_type: FileType.PDF,
    file_url: "url4",
    chapter: 1,
    class: 11,
    type: MaterialType.MATERIAL,
    category: MaterialCategory.JEE,
  },

  // NCERT Materials
  {
    id: 5,
    name: "Periodic Table",
    file_type: FileType.VIDEO,
    file_url: "url5",
    chapter: 1,
    class: 8,
    type: MaterialType.MATERIAL,
    category: MaterialCategory.NCERT,
  },
  {
    id: 6,
    name: "Acids, Bases and Salts",
    file_type: FileType.PDF,
    file_url: "url6",
    chapter: 2,
    class: 7,
    type: MaterialType.MATERIAL,
    category: MaterialCategory.NCERT,
  },
  {
    id: 7,
    name: "Chemical Reactions PYQ",
    file_type: FileType.PDF,
    file_url: "url7",
    chapter: 3,
    class: 10,
    type: MaterialType.PYQ,
    category: MaterialCategory.NCERT,
  },
  {
    id: 8,
    name: "Carbon Compounds",
    file_type: FileType.PDF,
    file_url: "url8",
    chapter: 4,
    class: 10,
    type: MaterialType.SOLUTION,
    category: MaterialCategory.NCERT,
  },

  // NEET Materials
  {
    id: 9,
    name: "Biomolecules Notes",
    file_type: FileType.PDF,
    file_url: "url9",
    chapter: 1,
    class: 12,
    type: MaterialType.MATERIAL,
    category: MaterialCategory.NEET,
  },
  {
    id: 10,
    name: "Biological Classification",
    file_type: FileType.PDF,
    file_url: "url10",
    chapter: 2,
    class: 11,
    type: MaterialType.MATERIAL,
    category: MaterialCategory.NEET,
  },
  {
    id: 11,
    name: "Human Physiology PYQ",
    file_type: FileType.PDF,
    file_url: "url11",
    chapter: 3,
    class: 11,
    type: MaterialType.PYQ,
    category: MaterialCategory.NEET,
  },

  // Olympiad Materials
  {
    id: 12,
    name: "Advanced Organic Chemistry",
    file_type: FileType.PDF,
    file_url: "url12",
    chapter: 1,
    class: null,
    type: MaterialType.MATERIAL,
    category: MaterialCategory.OLYMPIAD,
  },
  {
    id: 13,
    name: "Chemical Kinetics Advanced",
    file_type: FileType.PDF,
    file_url: "url13",
    chapter: 2,
    class: null,
    type: MaterialType.MATERIAL,
    category: MaterialCategory.OLYMPIAD,
  },
  {
    id: 14,
    name: "Previous Year NSO Papers",
    file_type: FileType.PDF,
    file_url: "url14",
    chapter: null,
    class: null,
    type: MaterialType.PYQ,
    category: MaterialCategory.OLYMPIAD,
  },

  // CUET Materials
  {
    id: 15,
    name: "General Chemistry",
    file_type: FileType.PDF,
    file_url: "url15",
    chapter: 1,
    class: 12,
    type: MaterialType.MATERIAL,
    category: MaterialCategory.CUET,
  },
  {
    id: 16,
    name: "CUET Chemistry PYQ",
    file_type: FileType.PDF,
    file_url: "url16",
    chapter: null,
    class: 12,
    type: MaterialType.PYQ,
    category: MaterialCategory.CUET,
  },

  // NTSE Materials
  {
    id: 17,
    name: "Chemistry Concepts for NTSE",
    file_type: FileType.PDF,
    file_url: "url17",
    chapter: null,
    class: 10,
    type: MaterialType.MATERIAL,
    category: MaterialCategory.NTSE,
  },
  {
    id: 18,
    name: "NTSE Previous Papers",
    file_type: FileType.PDF,
    file_url: "url18",
    chapter: null,
    class: 10,
    type: MaterialType.PYQ,
    category: MaterialCategory.NTSE,
  },
];
